name: BumpVersion

on:
    - push
    - pull_request

jobs:
    bump:
        if: ${{ github.event_name == 'push' }}
        runs-on: ubuntu-20.04
        steps:
            - name: Checkout branch
              uses: actions/checkout@v3
              with:
                fetch-depth: 0
            - uses: go-semantic-release/action@v1
            - run: | 
                VERSION=$(git describe --tags $(git rev-list --tags --max-count=1))
                echo ${VERSION//v}
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    bump2:
        runs-on: ubuntu-20.04
        steps:
            - name: Checkout branch
              uses: actions/checkout@v3
    bump3:
        runs-on: ubuntu-20.04
        steps:
            - name: Checkout branch
              uses: actions/checkout@v3
